### ISSUE TITLE
Autobuy issue

### ISSUE THREAD

**Issue by b3ll0v1c** [pcomputo/Whole-Foods-Delivery-Slot#36]
Hi there,

First off, thanks for putting this script together. I got this error consistently. I wonder if you or anyone else is getting it too. 

whole_foods_delivery_autobuy.py throws an exception after it finds an open slot. Below is the trace. It looks like the button the script is trying to click is not clickable. I don't have the page source handy but I'll save it next time it fails.

-Al

SLOTS OPEN!
Traceback (most recent call last):
  File "whole_foods_delivery_autobuy.py", line 120, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_autobuy.py", line 103, in getWFSlot
    autoCheckout(driver)
  File "whole_foods_delivery_autobuy.py", line 20, in autoCheckout
    slot_select_button.click()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-pressed="false" class="a-button-text ufss-slot-toggle-native-button" type="button">...</button> is not clickable at point (594, 609). Other element would receive the click: <div class="ufss-overview-container">...</div>
  (Session info: chrome=81.0.4044.92)

**Comment by mattmeng87** [comment]
I also had this problem. I'll save if it fails too.

**Comment by pcomputo** [comment]
sorry about that. Can you please try maximizing the window? It may not have a problem then.  The Chrome window is launched by the script, please maximize it. It's odd since the script should do it manually. Let me look into this.

**Comment by mattmeng87** [comment]
!
Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 21, in autoCheckout
    slot_select_button = driver.find_element_by_xpath('/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[1]/div[4]/div[2]/div/div[3]/div/div/ul/li/span/span/div/div[2]/span/span/button')
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[1]/div[4]/div[2]/div/div[3]/div/div/ul/li/span/span/div/div[2]/span/span/button"}
  (Session info: chrome=81.0.4044.92)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 124, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 107, in getWFSlot
    autoCheckout(driver)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 26, in autoCheckout
    slot_select_button.click()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-pressed="false" class="a-button-text ufss-slot-toggle-native-button" type="button">...</button> is not clickable at point (698, 528). Other element would receive the click: <div class="ufss-overview-container">...</div>
  (Session info: chrome=81.0.4044.92)

>>> 

I believe it was maximized. Not 100% though, it beeped I still got my order through so thank you :) 
Ill make sure its maximized and rerun this.

**Comment by pcomputo** [comment]
I just checked the script, its working end to end on my end. I'm not sure what's causing that problem.
I increased the sleep time for just in case, if you pull the latest changes.

**Comment by mattmeng87** [comment]
I thank you for the script! I don't know how to code or much about python so this took me a couple hours to get running so it very well could be on my end.

**Comment by joelnale** [comment]
Hi when I run in the CMD: python whole_foods_delivery_autobuy_windows.py

I get the following error:
c:\amz>python whole_foods_delivery_autobuy.py
  File "whole_foods_delivery_autobuy.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Can you advise?

**Comment by mattmeng87** [comment]
Ok your update seemed to have allowed it to click at least. I got to the next screen with the script now but it doesnt hit continue purchase after.

Warning (from warnings module):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 83
    soup = bs4.BeautifulSoup(html)
UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 83 of the file C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

SLOTS OPEN!
Clicked open slot
Selected slot and continued to next page
Found a slot but it got taken, run script again.
Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 42, in autoCheckout
    payment_select_continue = driver.find_element_by_xpath('/html/body/div[5]/div[1]/div[2]/div[2]/div[4]/div/form/div[3]/div[1]/div[2]/div/div/div/div[1]/span/span/input')
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[5]/div[1]/div[2]/div[2]/div[4]/div/form/div[3]/div[1]/div[2]/div/div/div/div[1]/span/span/input"}
  (Session info: chrome=81.0.4044.92)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 124, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 107, in getWFSlot
    autoCheckout(driver)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38-32\Scripts\whole_foods_delivery_autobuy_windows.py", line 61, in autoCheckout
    winsound.Beep(freq, duration)
NameError: name 'freq' is not defined

html parser have anything to do with it?

**Comment by pcomputo** [comment]
no not really. The script did run and get a slot but by the time it reached the checkout slot, the slot got taken by someone else. It needed a variable called freq. Pushed latest commits.

**Comment by b3ll0v1c** [comment]
@pcomputo That is exactly what happens all the time. I get the slot, the credit card is already selected,  and I get to the point where I place the order \but then the order does not go through and I am back to square one. Irritating. What is the freq variable for?

**Comment by mattmeng87** [comment]
well the script ran and it showed 1 slot it refreshed and had 2 slots it then chose a slot and then left me there. Slot wasn't actually taken I was here so I manually ordered so I know it worked it just didnt finish the order. I will run again and tell you results

**Comment by mattmeng87** [comment]
Ok ran again with updated. It did the same thing. The script is saying that the slot was taken but it actually does click on the slot and move to the next page but from there it seems like it thinks someone else took the slot. I can click continue manually and then one more click to finish the order.

**Comment by pcomputo** [comment]
You need to let the script run. After selecting a button and going to the next page, the script sleeps to let the page load. Sit back and dont touch anything till you see an error on the terminal. It will work till the end.

**Comment by b3ll0v1c** [comment]
@pcomputo Still does not work. Even leaving the window untouched and with the latest pull the same error appears:

selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-pressed="false" class="a-button-text ufss-slot-toggle-native-button" type="button">...</button> is not clickable at point (656, 636). Other element would receive the click: <div class="ufss-overview-container">...</div>
  (Session info: chrome=81.0.4044.92)

You mentioned it works for you. I saw you increase the wait time to allow the page to fully load. Looking at the error message and doing some research, it appears that the element the script is trying to click is behind another element, hence the error. Or it may be further wrapped in a div or span.

**Comment by pcomputo** [comment]
keep trying `git pull` to make sure you are on the latest version of the code. I added an explicit scroll to make sure the element is visible, if it doesnt maximize.

**Comment by b3ll0v1c** [comment]
That is exactly the issue. Even when maximized the element may not be visible depending on the resolution. I manually scrolled the page to the end and it stays that way, so it appears that hurdle has been solved. I'll git pull to get the new version that does the scroll. Thanks.
