### ISSUE TITLE
autobuy does not complete the process

### ISSUE THREAD

**Issue by b3ll0v1c** [pcomputo/Whole-Foods-Delivery-Slot#42]
whole_foods_delivery_autobuy.py consistently gives out the message:

SLOTS OPEN! 2
Selected slot and continued to next page
Found a slot but it got taken, run script again.

when in reality in the browser window it is showing "Select a payment method" page and waiting for the script to click continue. 

It looks like it fails around line 49-50 and through an exception. Maybe the page takes longer than 4 seconds to load and so it does not find the element listed in driver.find_element_by_xpath.

**Comment by mark-thompson** [comment]
@b3ll0v1c give [this repo](https://github.com/mark-thompson/whole-foods-deliverance) a shot. You should be able to successfully check out regardless of redirection to the payment selection page

**Comment by psg980** [comment]
I had a similar error:
SLOTS OPEN!
Traceback (most recent call last):
  File "e:\Whole-Foods-Delivery-Slot-master\whole_foods_delivery_autobuy_windows.py", line 128, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "e:\Whole-Foods-Delivery-Slot-master\whole_foods_delivery_autobuy_windows.py", line 124, in getWFSlot
    autoCheckout(driver)
  File "e:\Whole-Foods-Delivery-Slot-master\whole_foods_delivery_autobuy_windows.py", line 28, in autoCheckout
    slot_select_button = driver.find_element_by_xpath('/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[1]/div[4]/div[2]/div/div[4]/div/div/ul/li/span/span/div/div[2]/span/span/button')
  File "c:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "c:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "c:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[1]/div[4]/div[2]/div/div[4]/div/div/ul/li/span/span/div/div[2]/span/span/button"}
  (Session info: chrome=81.0.4044.92)

**Comment by b3ll0v1c** [comment]
> @b3ll0v1c give [this repo](https://github.com/mark-thompson/whole-foods-deliverance) a shot. You should be able to successfully check out regardless of redirection to the payment selection page

@mark-thompson I actually am, as of last night. I looked at your code, btw. Very nicely written!

**Comment by psg980** [comment]
Was this fixed? I don't see a difference between the whole_foods_delivery_autobuy_windows.py code I ran vs what is in the repo.
