### ISSUE TITLE
Element Click intercepted

### ISSUE THREAD

**Issue by sudovinh** [pcomputo/Whole-Foods-Delivery-Slot#44]
Ran to this using the auto buy. Lucky I was on the computer and was able to click the button and buy right away. Just wanted to report this.

```
refreshed
refreshed
refreshed
refreshed
refreshed
refreshed
refreshed
refreshed
refreshed
SLOTS OPEN! 2
Traceback (most recent call last):
  File "whole_foods_delivery_autobuy.py", line 130, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_autobuy.py", line 113, in getWFSlot
    autoCheckout(driver)
  File "whole_foods_delivery_autobuy.py", line 23, in autoCheckout
    slot_select_button.click()
  File "/Users/vinny/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/vinny/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/vinny/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/vinny/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-pressed="false" class="a-button-text ufss-slot-toggle-native-button" type="button">...</button> is not clickable at point (744, 736). Other element would receive the click: <div class="ufss-overview-container">...</div>
  (Session info: chrome=81.0.4044.92)
```

**Comment by pcomputo** [comment]
did this work on your end?
