### ISSUE TITLE
autobuy script throwing "continue not properly in loop" error

### ISSUE THREAD

**Issue by jswhitty** [pcomputo/Whole-Foods-Delivery-Slot#55]
Apologies for the non-python-literate question. 

My whole_foods_delivery_slot_chrome.py works fine. Now trying to get the autobuy.py script to work. Here's the error:

Whole-Foods-Delivery-Slot-master $ python whole_foods_delivery_autobuy.py
  File "whole_foods_delivery_autobuy.py", line 48
    continue
SyntaxError: 'continue' not properly in loop

**Comment by pcomputo** [comment]
its solved

**Comment by jswhitty** [comment]
hi Pooja,

I hope you are well! Thanks for any help on this...I'm not sure it is even an error.

Here's what I'm getting:

air-2:Whole-Foods-Delivery-Slot-master johnwhitty$ python whole_foods_delivery_autobuy.py
refreshed
SLOTS OPEN!
Found a slot but it got taken, run script again.
Traceback (most recent call last):
  File "whole_foods_delivery_autobuy.py", line 141, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_autobuy.py", line 138, in getWFSlot
    autoCheckout(driver)
  File "whole_foods_delivery_autobuy.py", line 42, in autoCheckout
    slot_continue_button = driver.find_element_by_xpath('/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[2]/div[3]/div/span/span/span/input')
  File "/Users/johnwhitty/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/johnwhitty/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/johnwhitty/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/johnwhitty/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[2]/div[3]/div/span/span/span/input"}
  (Session info: chrome=81.0.4044.122)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
