### ISSUE TITLE
Autobuy issue? slots open, but it got taken

### ISSUE THREAD

**Issue by jswhitty** [pcomputo/Whole-Foods-Delivery-Slot#57]
Not sure this a problem. Here's what I'm getting:

:Whole-Foods-Delivery-Slot-master $ python whole_foods_delivery_autobuy.py
refreshed
SLOTS OPEN!
Found a slot but it got taken, run script again.
Traceback (most recent call last):
  File "whole_foods_delivery_autobuy.py", line 141, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_autobuy.py", line 138, in getWFSlot
    autoCheckout(driver)
  File "whole_foods_delivery_autobuy.py", line 42, in autoCheckout
    slot_continue_button = driver.find_element_by_xpath('/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[2]/div[3]/div/span/span/span/input')
  File "/Users/johnwhitty/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/johnwhitty/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/johnwhitty/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/johnwhitty/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[2]/div[3]/div/span/span/span/input"}
  (Session info: chrome=81.0.4044.122)

**Comment by amohap2** [comment]
Do you have a screenshot of web page

**Comment by jswhitty** [comment]
[Screen Shot 2020-04-22 at 1.34.51 PM.png]

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pcomputo** [comment]
I increased the wait time. Its working correctly end to end for me. I don't see this issue. It could be the internet speeds varying.

**Comment by jswhitty** [comment]
OK. Thanks a bunch!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pcomputo** [comment]
if it still tends to throw error: increase "time.sleep(6)" to maybe "time.sleep(10)" or so... I really hope that resolves it.

**Comment by jswhitty** [comment]
I'll try it. Thanks.

Sent from ProtonMail mobile

-------- Original Message --------
