### ISSUE TITLE
Autobuy -- didn't click free slot

### ISSUE THREAD

**Issue by amohap2** [pcomputo/Whole-Foods-Delivery-Slot#58]
The time slot was found but the 2 hour window wasn't clicked. Here's stacktrace:
SLOTS OPEN! 2
Traceback (most recent call last):
  File "whole_foods_delivery_autobuy.py", line 137, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_autobuy.py", line 119, in getWFSlot
    autoCheckout(driver)
  File "whole_foods_delivery_autobuy.py", line 27, in autoCheckout
    slot_select_button.click()
  File "/Users/amol/.pyenv/versions/2.7.16/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/amol/.pyenv/versions/2.7.16/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/amol/.pyenv/versions/2.7.16/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/amol/.pyenv/versions/2.7.16/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-pressed="false" class="a-button-text ufss-slot-toggle-native-button" type="button">...</button> is not clickable at point (327, 631). Other element would receive the click: <div class="ufss-overview-container">...</div>
  (Session info: chrome=81.0.4044.122)

**Comment by pcomputo** [comment]
Is this resolved?
